local k = EXTRALEADER .. EXTRALEADER .. "k"
local l = EXTRALEADER .. EXTRALEADER .. "l"
local m = EXTRALEADER .. EXTRALEADER .. "m"
local n = EXTRALEADER .. EXTRALEADER .. "n"
local o = EXTRALEADER .. EXTRALEADER .. "o"

local K = EXTRALEADER .. EXTRALEADER .. "K"
local L = EXTRALEADER .. EXTRALEADER .. "L"
local M = EXTRALEADER .. EXTRALEADER .. "M"
local N = EXTRALEADER .. EXTRALEADER .. "N"
local O = EXTRALEADER .. EXTRALEADER .. "O"

