local p = EXTRALEADER .. EXTRALEADER .. "p"
local q = EXTRALEADER .. EXTRALEADER .. "q"
local r = EXTRALEADER .. EXTRALEADER .. "r"
local s = EXTRALEADER .. EXTRALEADER .. "s"
local t = EXTRALEADER .. EXTRALEADER .. "t"

local P = EXTRALEADER .. EXTRALEADER .. "P"
local Q = EXTRALEADER .. EXTRALEADER .. "Q"
local R = EXTRALEADER .. EXTRALEADER .. "R"
local S = EXTRALEADER .. EXTRALEADER .. "S"
local T = EXTRALEADER .. EXTRALEADER .. "T"

