local u = EXTRALEADER .. EXTRALEADER .. "u"
local v = EXTRALEADER .. EXTRALEADER .. "v"
local w = EXTRALEADER .. EXTRALEADER .. "w"
local x = EXTRALEADER .. EXTRALEADER .. "x"
local y = EXTRALEADER .. EXTRALEADER .. "y"
local z = EXTRALEADER .. EXTRALEADER .. "z"

local U = EXTRALEADER .. EXTRALEADER .. "U"
local V = EXTRALEADER .. EXTRALEADER .. "V"
local W = EXTRALEADER .. EXTRALEADER .. "W"
local X = EXTRALEADER .. EXTRALEADER .. "X"
local Y = EXTRALEADER .. EXTRALEADER .. "Y"
local Z = EXTRALEADER .. EXTRALEADER .. "Z"

