require("keymaps.leader.a_e")
require("keymaps.leader.f_j")
require("keymaps.leader.k_o")
require("keymaps.leader.p_t")
require("keymaps.leader.u_z")

require("keymaps.leader_2.a_e")
require("keymaps.leader_2.f_j")
require("keymaps.leader_2.k_o")
require("keymaps.leader_2.p_t")
require("keymaps.leader_2.u_z")

require("keymaps.localleader.a_e")
require("keymaps.localleader.f_j")
require("keymaps.localleader.k_o")
require("keymaps.localleader.p_t")
require("keymaps.localleader.u_z")

require("keymaps.localleader_2.a_e")
require("keymaps.localleader_2.f_j")
require("keymaps.localleader_2.k_o")
require("keymaps.localleader_2.p_t")
require("keymaps.localleader_2.u_z")

require("keymaps.extraleader.a_e")
require("keymaps.extraleader.f_j")
require("keymaps.extraleader.k_o")
require("keymaps.extraleader.p_t")
require("keymaps.extraleader.u_z")

require("keymaps.extraleader_2.a_e")
require("keymaps.extraleader_2.f_j")
require("keymaps.extraleader_2.k_o")
require("keymaps.extraleader_2.p_t")
require("keymaps.extraleader_2.u_z")

require("keymaps.bufleader.lsp")
require("keymaps.bufleader.neo_tree")
require("keymaps.bufleader.telescope")

