COMPLETEOPT = "menu,menuone,noinsert"
COMPLETEOPT_MAX_WIDTH = 40
COMPLETEOPT_MIN_WIDTH = 40

LOADED_ICON = " "
PENDING_ICON = "󱗽 "
UNLOADED_ICON = " "

UI_WIDTH = 0.7
UI_HEIGHT = 0.8
UI_TITLE_POSITION = "center"
UI_BORDER_STYLE = { "╭", "─", "╮", "│", "╯", "─", "╰", "│" }
UI_WINDOW_BLEND = 7

TELESCOPE_LAYOUT_STRATEGY = "flex"
TELESCOPE_SORTING_STRATEGY = "descending"
TELESCOPE_UI_PREVIEW_CUTOFF = "40"
TELESCOPE_UI_PREVIEW_WIDTH = 0.40
TELESCOPE_PROMPT_PREFIX = ""
TELESCOPE_PROMPT_TITLE = ""
TELESCOPE_SELECTION_CARET = " "
TELESCOPE_RESULTS_TITLE = "Results"

